openapi: '3.0.3'
info:
  title: Implement Gemini API
  version: '1.0'
servers:
  - url: http://localhost:8080/api/v1
paths:
  /generate-text:
    post:
      tags:
          - Gemini API
      description: Generate text using Gemini AI
      summary: Generate text using Gemini AI
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  example: "Apa itu Knowledge Graph?"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  status:
                    type: string
                    example: "OK"
                  result:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 400
                  status:
                    type: string
                    example: "Bad Request"
                  message:
                    type: string
                    example: "Prompt is required"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 500
                  status:
                    type: string
                    example: "Internal Server Error"
                  result:
                    type: string

